language: rust
cache: cargo
matrix:
    include:
        - os: linux
          dist: xenial
        - os: osx
addons:
    apt:
        packages:
            - libasound2-dev
script:
    - cargo build --release
before_deploy:
    - mv target/release/dos-emulator dos-emulator
    - strip dos-emulator
    - zip $TRAVIS_OS_NAME.zip dos-emulator config.toml
deploy:
    edge: true
    provider: releases
    token: $GITHUB_TOKEN
    file: $TRAVIS_OS_NAME.zip
    on:
        tags: true
